<div class="content_box">
<div class="innerBox">
	<h3>高级管理员命令行 [需开启上帝模式]</h3>
	<form id="form_admin_command" action="/admin/index/debug" method="POST">
		$ <input type="text" id="admin_command" name="command" />
		<div id="admin_command_result"></div>
	</form>
	<script>
		$(document).ready(function(){
			$('#form_admin_command').submit(function() {
				$.post($(this).attr('action'), $(this).serialize(), function(data){
					$("#admin_command_result").append(data);
					//$('#admin_command').val('');
				});
				return false;
			});
		});
	</script>
</div>
</div>
