<div class="content_box grid_9_3 toolsBox">
	<h2>让写日记更轻松</h2>
	<div class="column">
		<div class="thumbnail">
			<a href="#"><img width="244" height="174" alt="" src="/images/static/email-post.jpg"></a>
		</div>
		<h4><a href="#">邮件发布</a> <span>beta</span></h4>
		<p>你可以使用注册邮箱给我们发送一封邮件的形式来更新你的日记. <p>
    	<p class="insert_text"><input type="text" onclick="this.select();" readonly="readonly" value="eriji01@163.com"></input></p>
	</div>
	
	<div class="column">
		<div class="thumbnail">
			<a href="#"><img width="244" height="174" alt="" src="/images/static/msn-post.jpg"></a>
		</div>
		<h4><a href="#">MSN发布</a> <span>beta</span></h4>
		<p>你也可以使用MSN机器人, 只需发送一条消息给它即可更新日记. </p>
		<p class="insert_text"><input type="text" onclick="this.select();" readonly="readonly" value="eriji@live.com"></input></p>
	</div>
	
	<div class="column">
		<div class="thumbnail">
			<a href="#"><img width="244" height="174" alt="" src="/images/static/html5-post.jpg"></a>
		</div>
		<h4><a href="#">手机版(HTML5)</a> <span style="color:gray">Coming soon</span></h4>
		<p>你可以使用手机浏览器访问宜日记手机版网页, 随时随地书写当天日记.</p>
		<p class="insert_text"><input type="text" onclick="this.select();" readonly="readonly" value="m.eriji.com"></input></p>
	</div>
	
	<div style="height: 25px;" class="clear"></div>
	
	<div class="column">
		<div class="thumbnail">
			<a href="#"><img width="244" height="174" alt="" src="/images/static/notice-post.jpg"></a>
		</div>
		<h4><a href="#">定时提醒</a> <span>beta</span></h4>
		<p>你也可以使用<strong>定时提醒</strong>, 在收到通知时直接回复该邮件即可发布日记.<p>
		<p><a href="/user/settings/notice" class="blueBtn">设置提醒</a></p>
	</div>
	
	<div class="column">
		<div class="thumbnail">
			<a href="#"><img width="244" height="174" alt="" src="/images/static/tsina-post.jpg"></a>
		</div>
		<h4><a href="#">微博发布</a> <span style="color:gray">Coming soon</span></h4>
		<p>你也可以使用微博机器人, 发送一封私信给它即可更新日记. </p>
		<p><a href="http://t.sina.com.cn/eriji/" class="blueBtn">@宜日记</a></p>
	</div>
	
	<div class="column">
		<div class="thumbnail">
			<a href="#"><img width="244" height="174" alt="" src="/images/static/android-post.jpg"></a>
		</div>
		<h4><a href="#">Android客户端</a> <span style="color:gray">Coming soon</span></h4>
		<p>你可以下载我们的Android客户端, 支持编辑日记/上传照片.</p>
		<p><a href="#" class="blueBtn">下载 v0.1</a></p>
	</div>
	
	<div style="height: 25px;" class="clear"></div>
</div><!-- /content_box -->