<div class="content">
    <div class="content_box">
        <div class="innerBox">
            <div class="">
                尊重每一个生命  <br />
                敬畏自然  <br />
                守候每一份回忆  --   《宜日记》 <br /><br />              
                宜日记提供绝对保密的网络日记本；<br />
                宜日记努力为每个用户创造一个写日记的心情； <br />
                宜日记用心记录您人生的点点滴滴，为您默默守候；<br />
            </div>
        </div>
    </div>
</div><!-- /content -->

<div class="sidebar">
    <div class="content_box index_loginModel">
        <div class="index_loginModel_header">
            <h3>用户登录</h3>
            <a href="/user/account/forgetpassword">忘记密码</a>
        </div>
        <div class="innerBox">
            <form id="form_index_login" action="/login" method="post" class="labelForm tinyForm">
                <div class="form_element">
                	<label for="email">用户名：</label>
                	<input type="text" class="text" id="email" name="email">
                </div>
                <div class="form_element">
                	<label for="password">密码：</label>
                	<input type="password" class="text" id="password" name="password">
                </div>
                <div class="form_element clearfix" style="margin-bottom:0">
                	<div class="remeberMe">
	                    <input type="checkbox" value="1" name="rememberMe">
	                    <span class="index_loginModel_rememberme">下次自动登陆</span>
                	</div>
                	<div class="submit">
		                <input type="submit" class="button index_loginModel_submit" value="登 录">
                	</div>
                </div>
            </form>
        </div>
        <div class="index_loginModel_footer">
            <a class="index_loginModel_footer_link" href="/register">还没有帐号？来注册一下吧～</a>
        </div>
    </div>
    <div class="content_box blog_post_list">
        <h3>使用帮助</h3>
        <ul>
            <li><a href="#">号外～摆摆特刊新鲜出炉～</a></li>
            <li><a href="#">新功能：小组藏书</a></li>
            <li><a href="#">书籍页面改版了！</a></li>
            <li><a href="#">非Chrome用户们，油猴脚本来了</a></li>
            <li><a href="#">低调的，Chrome扩展发布</a></li>
        </ul>
    </div>
</div><!-- /sidebar -->

<div class="clearfix"></div>
