<div class="diary_upload_box">
<?php if (isset($this->files)):?>
<ul id="diary_file_list" class="photo_list clearfix">
<?php foreach ($this->files as $file): ?>
	<?php $preview = Ediary_Image::rename($file['filepath'], Ediary_Image::DEFAULT_PATTERN); ?>
	<li>
		<a class="lightbox" rel="group1" href="<?php echo $file['filepath'] ?>">
			<img src="<?php echo $preview ?>" width="160" height="120" />
		</a>
		<p><?php echo $file['filename']?><a class="delete" href="/upload/index/delete?id=<?php echo $file['id'] ?>">&nbsp;</a></p>
		
	</li>
<?php endforeach; ?>
</ul>
<?php endif;?>

<form class="form_diary_upload" enctype="multipart/form-data">
	<input id="diary_file_upload" name="file_upload" type="file" />
	<div id="diary-upload-queue"></div>
	<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
</form>	
<!--script type="text/javascript" src="/js/jquery.uploadify/swfobject.js"></script-->
<!--script type="text/javascript" src="/js/jquery.uploadify/jquery.uploadify.v2.1.4.js"></script-->
<script type="text/javascript">
(function() {
	Ediary.Upload.init();
	
})();
</script>
</div>
<a class="toolbar-close-btn" href="#">&nbsp;close</a>
