<?php 
/*
array(
 array (
  'id' => string '896' (length=3)
  'title' => string 'title' (length=5)
  'content' => string 'content' (length=7)
  'weather' => string 'sunshine' (length=8)
  'mood' => string 'normal' (length=6)
  'status' => string '0' (length=1)
  'created_at' => string '2011-03-25 22:01:55' (length=19)
  'saved_at' => string '2011-03-25 22:01:55' (length=19)
  'user_id' => string '3' (length=1)
  'journal_id' => string '1' (length=1)
 )
);
*/
?>
<?php if (count($this->paginator)): ?>
<div class="diarys_list">
    <?php foreach ($this->paginator as $item): ?>
	<?php 
	    $date = new Zend_Date($item['created_date']);
	    $year = $date->get(Zend_Date::YEAR);
	    $month = $date->get(Zend_Date::MONTH_NAME);
	    $day = $date->get(Zend_Date::DAY_SHORT);
	?>
	<div class="diary_item clearfix">
		<!-- div class="diary_item_mete"><span><?php echo $item['created_at']?></span></div-->
		<div class="diary_item_mete">
			<span class="meta_year_month"><?php echo $year . ' - ' . $month?></span>
			<span class="meta_day"><?php echo $day?></span>
		</div>
		<div class="content_box diary_item_content">
			<div class="innerBox">
				<h4><?php echo $this->escape($item['title']) ?></h4>
			    <?php echo strip_tags($item['content'], '<p>') ?>
				<div class="diary_item_footer">
					<a href="<?php echo $this->baseUrl("/diary/") . $item['id'];?>">编辑</a>
				</div>
			</div>
		</div>
	</div>
    <?php endforeach; ?>
</div>
<?php else: ?>
<p>暂无日记.</p>
<?php endif; ?>