<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() . "\n"?>
<?php echo $this->headStyle() ?>
<?php echo $this->headLink() ?>
<link media="all" rel="stylesheet" href="/css/style.css"" type="text/css" />
<link media="all" rel="stylesheet" href="/css/index.css"" type="text/css" />
<!--[if lt IE 7]>
<link media="all" rel="stylesheet" href="/css/ie.css" type="text/css" />
<![endif]-->
<?php echo $this->headScript() ?>
</head>
<body class="frontpage">
<?php echo $this->layout()->content ?>
<?php echo $this->inlineScript() ?>
</body>
</html>
