<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /> 
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() . "\n"?>
<?php echo $this->headStyle() ?>
<?php echo $this->headLink() ?>
<link media="all" rel="stylesheet" href="/css/style.min.css"" type="text/css" />
<link media="all" rel="stylesheet" href="/css/index.min.css"" type="text/css" />
<!--[if lt IE 7]>
<link media="all" rel="stylesheet" href="/css/ie.css" type="text/css" />
<![endif]-->
<?php echo $this->headScript() ?>
</head>
<body class="frontpage">
<?php echo $this->layout()->content ?>
<?php echo $this->inlineScript() ?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5449227-6']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</body>
</html>
