<div class="inner">
	<h1 class="logo"><a href="/"><img alt="宜日记" src="/images/logo_v1.gif" /><span>宜日记</span></a></h1>
    <div class="user_info">
        <?php if (isset($this->user)): //登录用户 ?>
        
        <a class="" href="/logout">退出</a><span class="vr"></span>
        <a href="/diary/list">我的日记</a><span class="vr"></span>
        <a href="/diary">写日记</a><span class="vr"></span>
        <a href="/user/settings"><?php echo $this->user->email?></a>
        
        <?php else:  //游客 ?>
        
        <a class="" href="register">注册</a><span class="vr"></span>
        <a href="/login">登录</a>
        
        <?php endif;?>
    </div>
    <div id="notice" class="active"></div>
</div>
