<div id="stripe"></div>
<div class="inner"><a class="title" href="/"><span>宜日记</span></a>
<ul class="user_info">
<?php if (isset($this->user)): //登录用户 ?>
    <li><a href="/user/settings"><?php echo $this->user->email?></a></li> |
    <li><a href="/diary">写日记</a> |
    <li><a href="/diary/list">我的日记</a> |
    <li><a class="" href="/logout">退出</a></li> |
<?php else:  //游客 ?>
    <li><a href="/login">登录</a></li> |
    <li><a class="" href="register">注册</a></li>
<?php endif;?>
</ul>
<div id="notice" class="active"></div>
</div>
