<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() . "\n"?>
<?php echo $this->headStyle() ?>
<link media="all" rel="stylesheet" href="<?php echo $this->baseUrl("css/style.css")?>" type="text/css" />
<?php echo $this->headScript() ?>
</head>
<body>
<div id="wrapper" <?php if(isset($this->pageClass)) echo 'class="'.$this->pageClass.'"'; ?>">
    <div id="header"><?php echo $this->render('header.phtml') ?></div><!-- /header -->
    <div id="nav"><?php echo $this->placeholder('nav') ?></div><!-- /nav -->
    <div id="content"><?php echo $this->layout()->content ?></div><!-- /content -->
    <div id="footer" class="clearfix"><?php echo $this->render('footer.phtml') ?></div><!-- /footer -->
</div><!-- /wrapper -->
</body>
</html>
