<?php
$this->loadJquery();
$this->headLink()->appendStylesheet("/css/smoothness/jquery-ui-1.8.11.custom.css");
$this->headScript()->appendFile("/js/jquery-ui-1.8.11.custom.min.js");
$this->headScript()->appendFile("/js/jquery-simpleTabs-1.0.js");
$this->headScript()->appendFile("/js/ediary.js?v=1");
$this->headScript()->appendFile("/js/ediary-editor.js?v=1");
$this->headScript()->appendFile("/js/tiny_mce/tiny_mce.js");
$this->inlineScript()->appendScript('
$(document).ready(function(){
	Ediary.Pad.init();
	
	var params = { 
		dateFormat: "yy-mm-dd",
		dayNamesMin: ["日", "一", "二", "三", "四", "五", "六"],
		monthNames: ["一月", "二月", "三月", "四月", "五月", "六月","七月","八月","九月","十月","十一月","十二月"]
		
	};
	$("#datepicker-start").datepicker(params);
	$("#datepicker-end").datepicker(params);
	
	$("#editor-toolbar").simpleTabs({select: null, useId: true});
	
	// DEBUG
	$("#editor-btn-theme").trigger("click");
});
');
?>
<!-- Toolbar -->
<div id="editor-toolbar" class="toolbar">
	<ul class="toolbar-btns">
		<li><a href="#toolbar-tabs-create" id="" class="menu">新建</a></li>
		<li><a href="#toolbar-tabs-open" id="editor-btn-open" class="menu active">打开</a></li>
		<li><a href="#" id="editor-btn-save" class="menu">保存</a></li>
		<li><a href="#toolbar-tabs-upload" class="menu">附件</a></li>
		<li><a href="#toolbar-tabs-theme" id="editor-btn-theme" class="menu">主题</a></li>
	</ul>
	
	<div id="toolbar-tabs-create" class="innerBox">
		create
	</div>
	
	<div id="toolbar-tabs-open" class="innerBox">
		<div class="diarys_list_toolbar">
			<label for="">从</label>
			<input id="datepicker-start" type="text" name="" value="" />
			<label for="">到</label>
			<input id="datepicker-end" type="text" name="" value="" />
			<a id="diarys_list_filter" href="#" class="">查看</a>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<input type="text" name="" value="" />
			<label for="">搜索</label>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<a id="diarys_list_flash" href="#" class="">刷新</a>
		</div>
		<table class="Table" id="table_diary_list" width="100%">
			<thead>
				<tr>
					<th width="130">标题</th>
					<th>内容</th>
					<th width="150">最后更新</th>
					<th width="40">编辑</th>
					<th width="40">删除</th>
				</tr>
			</thead>
			<tbody></tbody> <!-- AJAX ZONE -->
		</table>
		<div class="diarys_list_footer">
			<a id="diarys_list_pre_page" href="#">上一页</a>
			<a id="diarys_list_next_page" href="#">下一页</a>
			<span id="diarys_list_pages"></span>
		</div>
	</div><!-- /tabs -->
	
	<div id="toolbar-tabs-upload" class="innerBox">
		upload
	</div>
	
	<div id="toolbar-tabs-theme" class="innerBox">
		<ul class="theme_list clearfix">
			<li><a class="preview-theme-btns" href="t0"><img src="/theme/t0/preview.jpg" />主题0</a></li>
			<li><a class="preview-theme-btns" href="t1"><img src="/theme/t1/preview.jpg" />主题1</a></li>
			<li><a class="preview-theme-btns" href="t2"><img src="/theme/t2/preview.jpg" />主题2</a></li>
			<li><a class="preview-theme-btns" href="t3"><img src="/theme/t3/preview.jpg" />主题3</a></li>
			<li><a class="preview-theme-btns" href="t4"><img src="/theme/t4/preview.jpg" />主题3</a></li>
		</ul>
		<div class="theme_list_footer">
			<a href="#" id="change-theme-btn" class="btn">保存</a>
			<a href="#" id="cannel-theme-btn">取消</a>
		</div>
	</div>
</div><!-- /toolbar -->

<!-- Editor -->
<div id="diary">
<div class="diary_wrapper">
<form id="form_diary" method="post" action="<?php echo $this->baseUrl("/diary/save") ?>">
	<div class="diary_header">
		<div class="title clearfix">
			<input id="diary_title" name="diary[title]" type="text" class="text" value="<?php echo $this->diary['title']; ?>" />
			<div class="diary_weather">
				<label for="diary_weather">天气</label>
				<input id="diary_weather" name="diary[weather]" type="text" class="text" value="晴" />
			</div>
		</div>
		<div class="lastupdate"><span class="icon_ok_16" id="diary_last_update_status">最后保存:</span> <span id="diary_last_update"><?php echo $this->diary['saved_at']?></span></div>
	</div><!-- /header -->
	
	<div class="diary_body">
		<div class="diary_container">
			<textarea id="diary_content" class="" rows="40" cols="60" name="diary[content]"><?php echo $this->diary['content']; ?></textarea>
		</div>
	</div><!-- /body -->
	
	<div class="diary_footer">
		<input type="submit" value="submit" class="hide" />
		<input id="diary_id" type="hidden" name="diary[id]" value="<?php echo $this->diary['id']; ?>" />
	</div><!-- footer -->
</form>
</div><!-- /diary_wrapper -->
</div><!-- /diary -->


<?php 
//var_dump($this->diary);

?>
