<?php
$this->loadJquery();
$this->headScript()->appendFile("/js/jquery.validate.js");
$this->headScript()->appendFile("/js/ediary.js?v=1");
$this->inlineScript()->appendScript('
$(document).ready(function(){
    Ediary.loadModule("Validator");
    
    $("#form_login").validate(Ediary.Validator.getLoginForm());
    $("#email").focus();
});
');
?>
<div id="login" class="content_box">
    <div class="login_main">
        <h2>登录</h2>
        <?php echo $this->error; ?>
        <?php echo $this->form; ?>
    </div>
    <div class="login_side">
        <p><a href="<?php echo $this->baseUrl("register") ?>">还没有帐户，点此注册</a></p>
    </div>
    <div class="clearfix"></div>
</div>
