<?php
$this->loadJquery();
$this->headScript()->appendFile("/js/jquery.validate.js");
$this->headScript()->appendFile("/js/ediary.js?v=1");
$this->inlineScript()->appendScript('
$(document).ready(function(){
    var i18n = Ediary.i18n;

    $("#form_login").validate({
        //debug : true, 	// do not submit the form

        errorElement: "span",
        rules : {
            email : {
                required: true,
                email: true
            },
            password : {
                required: true
            }
        },
        messages : {
            email : {
                required : i18n.EMAIL_IS_NULL,
                email    : i18n.EMAIL_INVALID
            },
            password : {
                required  : i18n.PASSWORD_IS_NULL
            }
        },
        success: function(label) {
            label.html("Ok!").addClass("valid");
        }
    }); //end of validate
});
');
?>
<div id="login" class="content_box">
    <div class="login_main">
        <h2>登录</h2>
        <?php echo $this->error; ?>
        <?php echo $this->form; ?>
    </div>
    <div class="login_side">
        <p><a href="<?php echo $this->baseUrl("register") ?>">还没有帐户，点此注册</a></p>
    </div>
    <div class="clearfix"></div>
</div>
