<?php
$this->loadJquery();
$this->headScript()->appendFile("/js/jquery.validate.js");
$this->headScript()->appendFile("/js/ediary.js?v=1");
$this->inlineScript()->appendScript('
$(document).ready(function(){
    Ediary.loadModule("Validator");
    
    $("#form_register").validate(Ediary.Validator.getRegisterForm());
    $("#email").focus();
});
');
?>
<div id="loginBox" class="content_box">
    <div class="login_main">
        <h2>注册帐号</h2>
        <p class="formTitle">宜日记提供绝对保密的个人网络日记本，欢迎注册使用！</p>
        <div class="error"><?php echo $this->error; ?></div>
        <?php echo $this->form; ?>
    </div>
    <div class="login_side">
        <p><a href="<?php echo $this->baseUrl("login") ?>">已有帐户，点此登陆</a></p>
    </div>
    <div class="clearfix"></div>
</div>
