<?php
$this->loadJquery();
$this->headScript()->appendFile("/js/jquery.validate.js");
$this->headScript()->appendFile("/js/ediary.js?v=1");
$this->inlineScript()->appendScript('
$(document).ready(function(){
    var i18n = Ediary.i18n;

    $("#form_register").validate({
        //debug : true, 	// do not submit the form

        errorElement: "span",
        rules : {
            email: {
                required: true,
                email: true,
                remote: "/user/account/exists"
            },
            password: {
                required: true,
                minlength: 8,
                alnum : true
            },
            rePassword: {
            	required: true,
            	equalTo : "#password",
            }
        },
        messages : {
            email : {
                required : i18n.EMAIL_IS_NULL,
                email    : i18n.EMAIL_INVALID,
                remote	 : "该电子邮件已经被注册"
            },
            password : {
                required  : i18n.PASSWORD_IS_NULL,
                alnum 	  : i18n.PASSWORD_INVALID,
                minlength : i18n.PASSWORD_TOO_SHORT
            },
            rePassword: {
                required  : i18n.PASSWORD_IS_NULL,
                equalTo	  : "两次输入的密码不一样"
            }
        },
        success: function(label) {
            label.html("Ok!").addClass("valid");
        }
    }); //end of validate
    
    $.ajax({
    	type: "GET",
    	url: "/user/account/exists",
    	success: function(data, textStatus, jqXHR) {
    		console.log(123);
    		var data = jQuery.parseJSON(data);
    		console.log(data);
    		console.log(data.name);
    	},
    	dataType: "json"
    });
    	
});
');
?>
<div id="loginBox" class="content_box">
    <div class="login_main">
        <h2>注册帐号</h2>
        <p class="formTitle">宜日记提供绝对保密的个人网络日记本，欢迎注册使用！</p>
        <?php echo $this->error; ?>
        <?php echo $this->form; ?>
    </div>
    <div class="login_side">
        <p><a href="<?php echo $this->baseUrl("login") ?>">已有帐户，点此登陆</a></p>
    </div>
    <div class="clearfix"></div>
</div>
