<?php
$this->loadJquery();
$this->headScript()->appendFile("/js/jquery.validate.js");
$this->headScript()->appendFile("/js/ediary.js");
$this->inlineScript()->appendScript('
$(document).ready(function(){
    var i18n = Ediary.i18n;

    $("#form_setttings").validate({
        //debug : true, 	// do not submit the form
        errorElement: "span",
        rules : {
            username : {
                regex: /^[\w\ ]+$/
            }
        },
        messages : {
        	username : {
        		regex: i18n.USERNAME_INVALID
            }
        },
        success: function(label) {
            label.html("Ok!").addClass("valid");
        }
    }); //end of validate
});
');
?>
<div id="login" class="content_box">
    <div class="login_main">
        <h2>修改设置</h2>
        <?php echo $this->error; ?>
        <form id="form_setttings" action="#" method="post" class="labelForm sForm">
        	<div class="element">
        		<label for="username">您的姓名 :</label>
        		<input name="username" type="text" class="text" value="" />
        		<?php echo $this->partial('form_error.phtml', array('form' => $this->form,'element' => 'username')); ?>
        	</div>
        	<div class="element">
        		<label>&nbsp;</label>
        		<input class="button" type="submit" value="确定" />
        	</div>
        </form>
    </div>
    <div class="login_side">
        <p><a href="<?php echo $this->baseUrl("register") ?>">还没有帐户，点此注册</a></p>
    </div>
    <div class="clearfix"></div>
</div>
