<?php
$this->loadJquery();
$this->headScript()->appendFile("/js/jquery.validate.js");
$this->headScript()->appendFile("/js/ediary/all.js");
$this->inlineScript()->appendScript('
$(document).ready(function(){
	var E = Ediary; E.loadModule("Validator");
	
    $("#form_settings").validate(E.Validator.getFormOptions("form_settings"));
    $("#ableToChangePassword").click(function(){
    	$("#password, #rePassword").removeAttr("readonly").removeAttr("disabled");
    	$(this).hide();
 		return false;
    });
});
');
?>
<div id="settings-tabs" class="content_box">
	<div class="contentBox_tabNav">
		<?php foreach($this->tabs as $i => $tab): ?>
		<a class="contentBox_tabNav_tab<?php if ($i == 0) {echo ' first';} if (isset($tab['current'])) {echo ' current'; }?>" href="<?php echo $tab['url'] ?>"><?php echo $tab['title'] ?></a>
		<?php endforeach; ?>
    </div>
    <div class="innerBox">
    	<?php if(isset($this->messages)): ?>
    	<div class="messages">
    	    <?php foreach($this->messages as $msg) { echo $msg; } ?>
    	</div>
    	<?php endif; ?>
    	
    	<!-- form_settings -->
    	<?php echo $this->form; ?>
    </div>
</div><!-- /settings-tabs -->
