<div id="toolbar-tabs-theme">
    <ul class="theme_list clearfix">
        <li><a class="preview-theme-btns" href="/user/settings/theme" title="t0"><img src="/theme/t0/preview.jpg" width="120" height="120" /></a></li>
        <li><a class="preview-theme-btns" href="/user/settings/theme" title="t1"><img src="/theme/t1/preview.jpg" width="120" height="120" /></a></li>
        <li><a class="preview-theme-btns" href="/user/settings/theme" title="t2"><img src="/theme/t2/preview.jpg" width="120" height="120" /></a></li>
        <li><a class="preview-theme-btns" href="/user/settings/theme" title="t3"><img src="/theme/t3/preview.jpg" width="120" height="120" /></a></li>
        <li><a class="preview-theme-btns" href="/user/settings/theme" title="t4"><img src="/theme/t4/preview.jpg" width="120" height="120" /></a></li>
    </ul>
    <div class="theme_list_footer">
        <a href="#" id="change-theme-btn" class="btn">保存</a>
    </div>
    <a class="toolbar-close-btn" href="#">&nbsp;close</a>
    <script type="text/javascript"> (function(window) { Ediary.ThemeManager.init(); })(window); </script>
</div><!-- /toolbar-tabs-theme -->
